accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('logout_success', views.LogoutSuccessView.as_view(), name='logout_success'),
]

kakeiboapp/urls.py
from django.urls import path
from . import views

app_name = 'kakeiboapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('addtotal', views.AddTotalView.as_view(), name='addtotal'),
    path('addpost', views.AddPostView.as_view(), name='addpost'),
    path('addsuccess', views.AddSuccessView.as_view(), name='add_success'),
    path('kakeibolist', views.KakeiboListView.as_view(), name='kakeibo_list'),
    path('kakeibolist/<str:category>', views.CategoryView.as_view(), name='category'),
    path('kakeibolist/detail/<int:pk>', views.DetailView.as_view(), name='detail'),
    path('kakeibolist/<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

kakeiboproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kakeiboapp.urls')),
    path('', include('accounts.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), name='password_reset_complete'),
]

kakeiboapp/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.
class KakeiboPost(models.Model):
    CATEGORY = (
        ('給料', '給料'),
        ('お小遣い', 'お小遣い'),
        ('家賃', '家賃'),
        ('水道光熱費', '水道光熱費'),
        ('通信費', '通信費'),
        ('食費', '食費'),
        ('日用品費', '日用品費'),
        ('交際費', '交際費'),
        ('交通費', '交通費'),
        ('教育費', '教育費'),
    )
    
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    date = models.DateField(verbose_name='日付')
    title = models.CharField(verbose_name='タイトル',max_length=50)
    amount = models.IntegerField(verbose_name='金額')
    comment = models.TextField(verbose_name='コメント')
    category = models.CharField(verbose_name='カテゴリ', max_length=30, choices=CATEGORY)
    
    def __str__(self):
        return self.title
    
class Total(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    bank = models.IntegerField(verbose_name="銀行")
    income = models.IntegerField(verbose_name="収入")
    outcome = models.IntegerField(verbose_name="支出")
    datetime = models.DateTimeField(verbose_name='日時', auto_now=True)

kakeiboapp/forms.py
from django import forms
from .models import KakeiboPost, Total

class KakeiboPostForm(forms.ModelForm):
    class Meta:
        model = KakeiboPost
        fields = ['date', 'title', 'amount', 'comment', 'category']
    date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    
class TotalForm(forms.ModelForm):
    class Meta:
        model = Total
        fields = ['bank', 'income', 'outcome']
                
class ContactForm(forms.Form):
    name = forms.CharField(label='お名前', widget=forms.Textarea(attrs={'cols':'30', 'rows':'1'}))
    email = forms.EmailField(label='メールアドレス', widget=forms.Textarea(attrs={'cols':'30', 'rows':'1'}))
    title = forms.CharField(label='件名', widget=forms.Textarea(attrs={'cols':'30', 'rows':'1'}))
    message = forms.CharField(label='メッセージ', widget=forms.Textarea(attrs={'cols': '70', 'rows': '15'}))
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルを入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージを入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control'

kakeiboapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, ListView, DetailView, DeleteView, FormView
from django.urls import reverse_lazy
from .forms import KakeiboPostForm, TotalForm, ContactForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import KakeiboPost, Total
from django.contrib import messages
from django.core.mail import EmailMessage

# Create your views here.
class IndexView(ListView):
    model = Total
    template_name = 'kakeiboapp/index.html'
    context_object_name = 'latest'
    
    def get_queryset(self):
        if self.request.user.is_authenticated:
            # ログイン済みならユーザーのデータを返す
            return Total.objects.filter(user=self.request.user).order_by('-datetime')[:1]
        else:
            # 未ログインなら空のクエリセットを返す
            return Total.objects.none()

@method_decorator(login_required, name='dispatch')
class AddTotalView(CreateView):
    model = Total
    form_class = TotalForm
    template_name = 'kakeiboapp/addtotal.html'
    success_url = reverse_lazy('kakeiboapp:add_success')
    
    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class AddPostView(CreateView):
    model = KakeiboPost
    form_class = KakeiboPostForm
    template_name = 'kakeiboapp/addpost.html'
    success_url = reverse_lazy('kakeiboapp:add_success')
    
    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)
    
class AddSuccessView(TemplateView):
    template_name = 'kakeiboapp/add_success.html'
    
@method_decorator(login_required, name='dispatch')
class KakeiboListView(ListView):
    model = KakeiboPost
    template_name = 'kakeiboapp/kakeibo_list.html'
    context_object_name = 'records'
    paginate_by = 4
    
    def get_queryset(self):
        # ユーザーごとの投稿を取得
        return KakeiboPost.objects.filter(user=self.request.user).order_by('-date')

@method_decorator(login_required, name='dispatch')
class CategoryView(ListView):
    template_name = 'kakeiboapp/kakeibo_list.html'
    context_object_name = 'records'
    paginate_by = 4
    
    def  get_queryset(self):
        category = self.kwargs['category']
        return KakeiboPost.objects.filter(category=category, user=self.request.user).order_by('date')
    
class DetailView(DetailView):
    template_name = 'kakeiboapp/detail.html'
    model = KakeiboPost
    context_object_name = 'records'
    
class DeleteView(DeleteView):
    model = KakeiboPost
    template_name = 'kakeiboapp/post_delete.html'
    success_url = reverse_lazy('kakeiboapp:kakeibo_list')
    
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)
    
class ContactView(FormView):
    template_name = 'kakeiboapp/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('kakeiboapp:contact')
    
    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject = 'お問い合わせ: {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nタイトル: {2}\nメッセージ: {3}'.format(name, email, title, message)
        from_email = 'admin@example.com'
        to_list = ['admin@example.com']
        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list,)
        message.send()
        messages.success(self.request, 'お問い合わせは正常に送信されました。')
        return super().form_valid(form)

kakeiboapp/templates/kakeiboapp/add_success.html
{% extends "base.html" %}
{% load static %}
{% block title %}追加完了{% endblock %}
{% block body %}<body>{% endblock %}
{% block header %}
<div id="logo">
	<h1><a href="{% url 'kakeiboapp:index'%}"><img src="{% static 'images/logo.png' %}" alt="SAMPLE COMPANY"></a></h1>
</div>
{% endblock header %}
{% block contents %}
    <section>
        <h2>追加完了</h2>
        <p><a href="{% url 'kakeiboapp:index' %}">トップページへ</a></p>
    </section>
{% endblock %}

kakeiboapp/templates/kakeiboapp/addpost.html
{% extends "base.html" %}
{% load static %}
{% block title %}追加{% endblock %}
{% block body %}<body>{% endblock %}
{% block header %}
<div id="logo">
	<h1><a href="{% url 'kakeiboapp:index'%}"><img src="{% static 'images/logo.png' %}" alt="SAMPLE COMPANY"></a></h1>
</div>
{% endblock header %}
{% block contents %}
<section>
    <form method="post">
        {% csrf_token %}
        <table class="ta1">
            {% comment %} <tr>
                <th>ユーザー</th>
                <td>{{form.user}}</td>
            </tr> {% endcomment %}
            <tr>
                <th>日付</th>
                <td>{{form.date}}</td>
            </tr>
            <tr>
                <th>タイトル</th>
                <td>{{form.title}}</td>
            </tr>
            <tr>
                <th>金額</th>
                <td>{{form.amount}}</td>
            </tr>
            <tr>
                <th>コメント</th>
                <td>{{form.comment}}</td>
            </tr>
            <tr>
                <th>カテゴリー</th>
                <td>{{form.category}}</td>
            </tr>
        </table>
        <br><p class="btn"><input type="submit" value="追加"></p>
    </form>
</section>
{% endblock contents %}

kakeiboapp/templates/kakeiboapp/addtotal.html
{% extends "base.html" %}
{% load static %}
{% block title %}追加{% endblock %}
{% block body %}<body>{% endblock %}
{% block header %}
<div id="logo">
	<h1><a href="{% url 'kakeiboapp:index'%}"><img src="{% static 'images/logo.png' %}" alt="SAMPLE COMPANY"></a></h1>
</div>
{% endblock header %}
{% block contents %}
<section>
    <form method="post">
        {% csrf_token %}
        <table class="ta1">
            <tr>
                <th>銀行残高</th>
                <td>{{form.bank}}</td>
            </tr>
            <tr>
                <th>収入</th>
                <td>{{form.income}}</td>
            </tr>
            <tr>
                <th>支出</th>
                <td>{{form.outcome}}</td>
            </tr>
        </table>
        <br><p class="btn"><input type="submit" value="追加"></p>
    </form>
</section>
{% endblock contents %}

kakeiboapp/templates/kakeiboapp/contact.html
{% extends "base.html" %}
{% load static %}
{% block title %}お問い合わせ{% endblock %}
{% block header%}
<div id="logo">
	<h1><a href="{% url 'kakeiboapp:index'%}"><img src="{% static 'images/logo.png' %}" alt="SAMPLE COMPANY"></a></h1>
</div>
{% endblock %}
{% block body %}<body>{% endblock %}
{% block contents%}
<section>
<h2>お問い合わせ</h2>

	<!-- フォームの送信が成功したときのメッセージを表示するためのコード -->
	<!-- requestにmessagesオブジェクトが存在している場合 -->
	{% if messages %}
	<!-- 箇条書きのスタイルを無効にした<ul>タグでメッセージを出力 -->
	<ul class="list-unstyled" style="list-style: none;">
	<!-- forでmessagesを取り出す -->
	{% for message in messages %}
	<!-- message.tagsが存在する場合はclass属性にCSSのクラスを設定 -->
	<li {%if message.tags %} class="{{ message.tags }}" {% endif %}>
		<!-- messageに格納されているメッセージを出力 -->
		{{ message }}
	</li>
	{% endfor %}
	</ul>
	{% endif %}
<form method="post">
{% csrf_token %}
<table class="ta1">
<tr>
<th>お名前※</th>
<td>{{form.name}}</td>
</tr>
<tr>
<th>メールアドレス※</th>
<td>{{form.email}}</td>
</tr>
<tr>
<th>件名※</th>
<td>{{form.title}}</td>
</tr>
<tr>
<th>お問い合わせ詳細※</th>
<td>{{form.message}}</td>
</tr>
</table>

<p class="btn">
<input type="submit" value="送信">
</p>
</form>

</section>
{% endblock %}

kakeiboapp/templates/kakeiboapp/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}詳細{% endblock %}
{% block header %}
<div id="logo">
	<h1><a href="{% url 'kakeiboapp:index'%}"><img src="{% static 'images/logo.png' %}" alt="SAMPLE COMPANY"></a></h1>
</div>
{% endblock %}
{% block body %}<body>{% endblock %}
{% block contents %}
<section>
    <h2>{{object.date}}詳細</h2>
    <table class="ta1">
        <tr>
            <th>タイトル</th>
            <td>{{object.title}}</td>
        </tr>
        <tr>
            <th>金額</th>
            <td>{{object.amount}}</td>
        </tr>
        <tr>
            <th>コメント</th>
            <td>{{object.comment}}</td>
        </tr>
        <tr>
            <th>カテゴリー</th>
            <td>{{object.category}}</td>
        </tr>
    </table>
    <p class="btn"><a href="{% url 'kakeiboapp:delete' object.pk %}" >削除する</a></p>
    <p class="btn"><a href="{% url 'kakeiboapp:kakeibo_list' %}">一覧に戻る</a></p>
</section>
{% endblock %}

kakeiboapp/templates/kakeiboapp/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}家計簿アプリ HOME{% endblock %}
{% block body %}<body class="home">{% endblock %}
{% block header %}
	<div id="logo">
	<h1><a href="{% url 'kakeiboapp:index' %}">家計簿アプリ</a></h1>
	{% if user.is_authenticated %}
	{% for item in latest %}
	<p>銀行: {{item.bank}}</p>
	<p>収入: {{item.income}}</p>
	<p>支出: {{item.outcome}}</p>
	{% endfor %}
	{% else %}
	<p><a href="{% url 'accounts:login' %}">ログイン</a></p>
	{% endif %}
	</div>
	<div id="mainimg">
		<video src="{% static 'images/mainimg.mp4' %}" autoplay loop muted playsinline>
	</div>
{% endblock %}

{% block contents %}
	<div class="c2">

	<div class="main">

	<section>

	<h2>NEWS</h2>

	<dl id="new">
	<dt>2022/10/13<span>その他</span></dt>
	<dd>tp_biz60配布開始。</dd>
	<dt>20XX/00/00<span class="icon-bg1">サービス</span></dt>
	<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
	<dt>20XX/00/00<span class="icon-bg1">サービス</span></dt>
	<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
	<dt>20XX/00/00</dt>
	<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
	<dt>20XX/00/00<span>その他</span></dt>
	<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。サンプルテキスト。サンプルテキスト。サンプルテキスト。サンプルテキスト。サンプルテキスト。サンプルテキスト。サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
	</dl>

	<a href="https://q19cms.com/files_m/file/cms_oshirase.html" target="_blank"><img src="https://template-party.com/file/images/cms_oshirase/banner_oshirase_cms2.jpg" alt="無料で使えるお知らせCMSのご案内"></a>

	</section>

	</div>

	</div>
	<!--/.c2-->

{% endblock %}

kakeiboapp/templates/kakeiboapp/kakeibo_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}リスト一覧{% endblock %}
{% block header %}
<div id="logo">
	<h1><a href="{% url 'kakeiboapp:index'%}"><img src="{% static 'images/logo.png' %}" alt="SAMPLE COMPANY"></a></h1>
</div>
{% endblock %}
{% block body %}<body>{% endblock %}
{% block contents %}
<section>
    <h2>一覧</h2>
    <table class="ta1">
    {% for record in records%}
        <tr>
            <th>{{record.date}}</th>
            <td>{{record.title}}</td>
            <td>{{record.amount}}</td>
            <td><button type="button" onclick="location.href='{% url 'kakeiboapp:category' record.category %}'">{{ record.category }}</button></td>
            <td><button type="button" onclick="location.href='{% url 'kakeiboapp:detail' record.pk %}'">詳細</button></td>
        </tr>
    {% endfor %}
    </table>
    {% include "kakeiboapp/pagination.html" %}
</section>
{% endblock %}

kakeiboapp/templates/kakeiboapp/pagination.html
<!-- ページネーションのアイコンを左右中央に配置 -->
<ul class="Pagination">
    <!--
    前ページを表示するアイコンとリンクの設定
    ページネーションされたPageオブジェクトをorderby_recordsで取得
    Page.has_previous: 直前にページがある場合にTrueを返す
    -->
    {% if page_obj.has_previous %}
    <!--
    前のページが存在する場合はそのページへのリンクが設定されたアイコン[<<]を表示
    Page.previous_page_number: 直前のページ番号を返す
    -->
    <li class="Pagination-Item">
        <a class="Pagination-Item-Link"
        　　 href="?page={{ page_obj.previous_page_number }}"
        　　 aria-label="Previous">
        <svg xmlns="http://www.w3.org/2000/svg" class="Pagination-Item-Link-Icon" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M11 19l-7-7 7-7m8 14l-7-7 7-7" />
        </svg>
        {% comment %} <span aria-hidden="true">&laquo;</span> {% endcomment %}
        </a>
    </li>
    {% endif %}
    <!--
     すべてのページについてページ番号のアイコンを表示
     paginator.page_range: [1, 2, 3, 4] のように1から始まるページ番号を返す
     page_obj.paginator.page_rangeとして取得
     ブロックパラメーターnumに順次取り出される
    -->
    {% for num in page_obj.paginator.page_range %}
        <!--
        各ページのアイコンを出力
        Page.number: 引き渡されたページのページ番号を返す
        -->
        <li class="Pagination-Item">
            <a class="Pagination-Item-Link" href="?page={{ num }}"><span>{{ num }}</span></a>
        </li>
    {% endfor %}
    <!--
    次ページへのリンクを示すアイコンの表示
    Page.has_next: 次のページがある場合にTrueを返す
    -->
    {% if page_obj.has_next %}
    <!--
    次ページが存在する場合はリンクを設定したアイコン［>>]を表示
    Page.next_page_number: 次のページ番号を返す
    -->
    <li class="Pagination-Item">
        <a class="Pagination-Item-Link" href="?page={{ page_obj.next_page_number }}">
            <svg xmlns="http://www.w3.org/2000/svg" class="Pagination-Item-Link-Icon" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
            </svg>
        </a>
    </li>
    {% endif %}
</ul>

kakeiboapp/templates/kakeiboapp/post_delete copy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>削除</title>
</head>
<body>
    <h1>削除</h1>
    <form method="POST">
        <br>
        <p>削除してもいいですか?</p>
        {% csrf_token %}
        <button type="submit">削除</button>
        <a href="{% url 'kakeiboapp:detail' object.pk %}">キャンセル</a>
    </form>
</body>
</html>

kakeiboapp/templates/kakeiboapp/post_delete.html
{% extends "base.html" %}
{% load static %}
{% block title %}削除{% endblock %}
{% block header %}
<div id="logo">
	<h1><a href="{% url 'kakeiboapp:index'%}"><img src="{% static 'images/logo.png' %}" alt="SAMPLE COMPANY"></a></h1>
</div>
{% endblock %}
{% block body %}<body>{% endblock %}
{% block contents %}
<section>
    <h2>削除</h2>
    <form method="post">
        <p>削除してもいいですか？</p>
        {% csrf_token %}
        <p class="btn"><input type="submit" value="削除"></p>
        <p class="btn"><a href="{% url 'kakeiboapp:detail' object.pk %}" >戻る</a></p>
    </form>
</section>
{% endblock %}

kakeiboapp/templates/kakeiboapp/total_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>kari</title>
</head>
<body>
    <h1>aa</h1>
</body>
</html>