accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('logout_success', views.LogoutSuccessView.as_view(), name='logout_success'),
]

kakeiboapp/urls.py
from django.urls import path
from . import views

app_name = 'kakeiboapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('addtotal', views.AddTotalView.as_view(), name='addtotal'),
    path('addpost', views.AddPostView.as_view(), name='addpost'),
    path('addsuccess', views.AddSuccessView.as_view(), name='add_success'),
    path('kakeibolist', views.KakeiboListView.as_view(), name='kakeibo_list'),
    path('kakeibolist/<str:category>', views.CategoryView.as_view(), name='category'),
    path('kakeibolist/detail/<int:pk>', views.DetailView.as_view(), name='detail'),
    path('kakeibolist/<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

kakeiboproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kakeiboapp.urls')),
    path('', include('accounts.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), name='password_reset_complete'),
]

kakeiboapp/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.
class KakeiboPost(models.Model):
    CATEGORY = (
        ('給料', '給料'),
        ('お小遣い', 'お小遣い'),
        ('家賃', '家賃'),
        ('水道光熱費', '水道光熱費'),
        ('通信費', '通信費'),
        ('食費', '食費'),
        ('日用品費', '日用品費'),
        ('交際費', '交際費'),
        ('交通費', '交通費'),
        ('教育費', '教育費'),
    )
    
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    date = models.DateField(verbose_name='日付')
    title = models.CharField(verbose_name='タイトル',max_length=50)
    amount = models.IntegerField(verbose_name='金額')
    comment = models.TextField(verbose_name='コメント')
    category = models.CharField(verbose_name='カテゴリ', max_length=30, choices=CATEGORY)
    
    def __str__(self):
        return self.title
    
class Total(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    bank = models.IntegerField(verbose_name="銀行")
    income = models.IntegerField(verbose_name="収入")
    outcome = models.IntegerField(verbose_name="支出")
    datetime = models.DateTimeField(verbose_name='日時', auto_now=True)

kakeiboapp/forms.py
from django import forms
from .models import KakeiboPost, Total

class KakeiboPostForm(forms.ModelForm):
    class Meta:
        model = KakeiboPost
        fields = ['date', 'title', 'amount', 'comment', 'category']
    date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    
class TotalForm(forms.ModelForm):
    class Meta:
        model = Total
        fields = ['bank', 'income', 'outcome']
                
class ContactForm(forms.Form):
    name = forms.CharField(label='お名前', widget=forms.Textarea(attrs={'cols':'30', 'rows':'1'}))
    email = forms.EmailField(label='メールアドレス', widget=forms.Textarea(attrs={'cols':'30', 'rows':'1'}))
    title = forms.CharField(label='件名', widget=forms.Textarea(attrs={'cols':'30', 'rows':'1'}))
    message = forms.CharField(label='メッセージ', widget=forms.Textarea(attrs={'cols': '70', 'rows': '15'}))
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルを入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージを入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control'

kakeiboapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, ListView, DetailView, DeleteView, FormView
from django.urls import reverse_lazy
from .forms import KakeiboPostForm, TotalForm, ContactForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import KakeiboPost, Total
from django.contrib import messages
from django.core.mail import EmailMessage

# Create your views here.
class IndexView(ListView):
    model = Total
    template_name = 'kakeiboapp/index.html'
    context_object_name = 'latest'
    
    def get_queryset(self):
        if self.request.user.is_authenticated:
            # ログイン済みならユーザーのデータを返す
            return Total.objects.filter(user=self.request.user).order_by('-datetime')[:1]
        else:
            # 未ログインなら空のクエリセットを返す
            return Total.objects.none()

@method_decorator(login_required, name='dispatch')
class AddTotalView(CreateView):
    model = Total
    form_class = TotalForm
    template_name = 'kakeiboapp/addtotal.html'
    success_url = reverse_lazy('kakeiboapp:add_success')
    
    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class AddPostView(CreateView):
    model = KakeiboPost
    form_class = KakeiboPostForm
    template_name = 'kakeiboapp/addpost.html'
    success_url = reverse_lazy('kakeiboapp:add_success')
    
    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)
    
class AddSuccessView(TemplateView):
    template_name = 'kakeiboapp/add_success.html'
    
@method_decorator(login_required, name='dispatch')
class KakeiboListView(ListView):
    model = KakeiboPost
    template_name = 'kakeiboapp/kakeibo_list.html'
    context_object_name = 'records'
    paginate_by = 4
    
    def get_queryset(self):
        # ユーザーごとの投稿を取得
        return KakeiboPost.objects.filter(user=self.request.user).order_by('-date')

@method_decorator(login_required, name='dispatch')
class CategoryView(ListView):
    template_name = 'kakeiboapp/kakeibo_list.html'
    context_object_name = 'records'
    paginate_by = 4
    
    def  get_queryset(self):
        category = self.kwargs['category']
        return KakeiboPost.objects.filter(category=category, user=self.request.user).order_by('date')
    
class DetailView(DetailView):
    template_name = 'kakeiboapp/detail.html'
    model = KakeiboPost
    context_object_name = 'records'
    
class DeleteView(DeleteView):
    model = KakeiboPost
    template_name = 'kakeiboapp/post_delete.html'
    success_url = reverse_lazy('kakeiboapp:kakeibo_list')
    
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)
    
class ContactView(FormView):
    template_name = 'kakeiboapp/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('kakeiboapp:contact')
    
    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject = 'お問い合わせ: {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nタイトル: {2}\nメッセージ: {3}'.format(name, email, title, message)
        from_email = 'admin@example.com'
        to_list = ['admin@example.com']
        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list,)
        message.send()
        messages.success(self.request, 'お問い合わせは正常に送信されました。')
        return super().form_valid(form)

kakeiboapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>{% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ここにサイト説明を入れます">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/destyle.css@3.0.2/destyle.min.css"> {% endcomment %}
</head>

{% block body %}{% endblock %}

<div id="container">

<header>
{% block header%}{% endblock %}
</header>

<!--開閉ブロック-->
<div id="menubar">

<nav>
{% if user.is_authenticated%}
<ul>
<li><a href="{% url 'kakeiboapp:index' %}">ホーム</a></li>
<li><a href="{% url 'kakeiboapp:kakeibo_list' %}">一覧</a></li>
<li><a href="">項目追加</a>
	<ul>
	<li><a href="{% url 'kakeiboapp:addtotal' %}">合計</a></li>
	<li><a href="{% url 'kakeiboapp:addpost' %}">リスト</a></li>
	</ul>
</li>
<li><a href="{% url 'kakeiboapp:contact' %}">お問い合わせ</a></li>
<li><a href="{% url 'accounts:logout' %}" id="logout-link">ログアウト</a></li>
<script>
	document.getElementById('logout-link').addEventListener('click', function (event) {
		event.preventDefault(); // デフォルトのリンク動作を無効化
		const csrftoken = getCookie('csrftoken'); // CSRFトークンを取得

		fetch("{% url 'accounts:logout' %}", {
			method: "POST",
			headers: {
				"X-CSRFToken": csrftoken, // CSRFトークンをヘッダーに追加
				"Content-Type": "application/json",
			},
		}).then(response => {
			if (response.ok) {
				window.location.href = "{% url 'accounts:logout_success' %}" ; // ログアウト後のリダイレクト先
			} else {
				alert("Logout failed!");
			}
		});
	});

	// CSRFトークンを取得する関数
	function getCookie(name) {
		let cookieValue = null;
		if (document.cookie && document.cookie !== '') {
			const cookies = document.cookie.split(';');
			for (let i = 0; i < cookies.length; i++) {
				const cookie = cookies[i].trim();
				if (cookie.startsWith(name + '=')) {
					cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
					break;
				}
			}
		}
		return cookieValue;
	}
</script>
</ul>
{% else %}
<ul>
<li><a href="{% url 'accounts:login' %}">ログイン</a></li>
<li><a href="{% url 'accounts:signup' %}">サインアップ</a></li>
<li><a href="{% url 'kakeiboapp:contact' %}">お問い合わせ</a></li>
</ul>
{% endif %}
</nav>
</div>
<!--/#menubar-->

<main>
{% block contents %}{% endblock %}
</main>

<footer>

<div class="copy">
<small>Copyright&copy; <a href="index.html">KAKEIBOAPP</a> All Rights Reserved.</small>
<span class="pr"><a href="https://template-party.com/" target="_blank">《Web Design:Template-Party》</a></span>
</div>

</footer>

<!--開閉ボタン（ハンバーガーアイコン）-->
<div id="menubar_hdr">
<span></span><span></span><span></span>
</div>

</div>
<!--/#container-->

<!--jQueryの読み込み-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!--パララックス（inview）-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/protonet-jquery.inview/1.1.2/jquery.inview.min.js"></script>
<script src="{% static 'js/jquery.inview_set.js' %}"></script>

<!--このテンプレート専用のスクリプト-->
<script src="{% static 'js/main.js' %}"></script>

<!--ページの上部へ戻るボタン-->
<div class="pagetop"><a href="#"><i class="fas fa-angle-double-up"></i></a></div>

</body>
</html>